version: "3.7"
services:
  mongodb:
    container_name: igbayesile_mongodb
    image: mongo
    restart: always
    volumes:
      - mongodb:/data/db
  
  redisdb:
    container_name: igbayesile_redisdb
    image: redis:alpine
    ports:
      - '6379:6379'

  api:
    image: igbayesile_api
    build:
      context: .
    ports:
      - 4000:4000
    depends_on:
      - mongodb
      - redisdb
volumes:
  mongodb:
