import InitializeConfigs from "@dashboard/components/initialize-configs";
import MainNavbar from "@dashboard/components/navigations/main-navbar";
import TopNavbar from "@dashboard/components/navigations/top-navbar";
import Providers from "@dashboard/components/providers";
import "@repo/ui/globals.css";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Dashboard",
  description: "Generated by create turbo",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}): JSX.Element {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <InitializeConfigs>
            <div className="lg:flex lg:flex-row lg:items-stretch">
              <div className="py-2 px-2 flex items-between justify-between flex-wrap border-input border-b lg:py-0 lg:px-0 lg:bg-muted/60 lg:shadow-lg lg:border-b-0">
                <MainNavbar />
                <div className="lg:hidden">
                  <TopNavbar />
                </div>
              </div>
              <div className="">
                <div className="hidden lg:block lg:sticky lg:top-0 lg:right-0 lg:bg-background">
                  <TopNavbar />
                </div>
                <div className="px-2 lg:px-4">{children}</div>
              </div>
            </div>
          </InitializeConfigs>
        </Providers>
      </body>
    </html>
  );
}
